# Generated by Django 5.0 on 2023-12-24 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeria", "0003_fotografia_publicada"),
    ]

    operations = [
        migrations.AddField(
            model_name="fotografia",
            name="data_foografia",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
