# Generated by Django 5.0 on 2023-12-26 02:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("galeria", "0004_fotografia_data_foografia"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fotografia",
            old_name="data_foografia",
            new_name="data_fotografia",
        ),
    ]
