# Generated by Django 5.0 on 2023-12-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeria", "0005_rename_data_foografia_fotografia_data_fotografia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotografia",
            name="foto",
            field=models.ImageField(blank=True, upload_to="fotos/%Y/%m/%d/"),
        ),
    ]
